### ISSUE TITLE
图片上传有错

### ISSUE THREAD

**Issue by dreamsleet** [woann/yamecent-admin#5]
路由:
//图片上传
   ` $route->post('upload', 'Admin\IndexController@upload');`

//图片上传
  `  $route->post('/admin/upload', 'Admin\IndexController@upload');`
很好的资源，新手已拿来学习中，感谢！ @woann @tksmai @xjj373047546

**Comment by tksmai** [comment]
#6

**Comment by tksmai** [comment]
Thanks for the report @dreamsleet  I've pull #6  to fix this.
