### ISSUE TITLE
想咨询下 这个后台目前可用于生产环境吗

### ISSUE THREAD

**Issue by lepig** [woann/yamecent-admin#8]
看项目好像只有1-2个人在开发。最近公司有个后台需求，也找了几个。但发现这个项目的UI我很喜欢，但活跃度好像不太高。 到时候怕遇到一些坑自己一时半会不能很快速的解决。

**Comment by woann** [comment]
可以用啊，这个项目不打算再更新了，没时间搞，这个没做什么深度的封装，就是最基本的在laravel的基础上写了一套后台管理。很容易二次开发的
